### ISSUE TITLE
Android 5.0 出现 Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x2040002

### ISSUE THREAD

**Issue by z-chu** [yidun/captcha-android-demo#14]
详细日志：
```java
Captcha.validate : android.view.InflateException: Binary XML file line #22: Error inflating class com.netease.nis.captcha.CaptchaWebView
at android.view.LayoutInflater.createView(LayoutInflater.java:633)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
at com.netease.nis.captcha.a.a(Unknown Source)
at com.netease.nis.captcha.Captcha.validate(Unknown Source)
at io.bithumb.android.login.utils.CaptchaExtKt.validate(CaptchaExt.kt:47)
at io.bithumb.android.login.utils.CaptchaExtKt.validate(CaptchaExt.kt:58)
......
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x2040002
at android.content.res.Resources.getText(Resources.java:274)
at android.content.res.Resources.getString(Resources.java:360)
at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:702)
at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:608)
at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:619)
at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:758)
at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:608)
at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:546)
at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:312)
at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:97)
at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:264)
at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:124)
at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:111)
at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:108)
at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:261)
at android.webkit.WebView.<init>(WebView.java:548)
at android.webkit.WebView.<init>(WebView.java:483)
at android.webkit.WebView.<init>(WebView.java:466)
at android.webkit.WebView.<init>(WebView.java:453)
at com.netease.nis.captcha.CaptchaWebView.<init>(Unknown Source)
... 28 more
```
[stackoverflow上的解决方式](https://stackoverflow.com/questions/41025200/android-view-inflateexception-error-inflating-class-android-webkit-webview)

因为这个问题直接导致sdk在5.0上无法使用

**Comment by z-chu** [comment]
由于无法修改sdk源码，目前我通过`LayoutInflater`拦截的方式修复了这个问题。

同样和我遇到这个问题的在SDK没有修复之前可以参考我的解决方式:

引入[viewpump](https://github.com/InflationX/ViewPump)

 `implementation  'io.github.inflationx:viewpump:2.0.3'`

创建继承`CaptchaWebView`的修复类
```kotlin
class LollipopFixedCaptchaWebView @JvmOverloads constructor(
    context: Context,
    attrs: AttributeSet? = null
) : CaptchaWebView(context.getFixedContext(), attrs)


private fun Context.getFixedContext(): Context {
    return if (Build.VERSION.SDK_INT in 21..22) createConfigurationContext(Configuration()) else this
}
```
在 `Application` 类的 `onCreate` 中添加
```kotlin
 if (Build.VERSION.SDK_INT in 21..22) {
            ViewPump.init(
                ViewPump.builder()
                    .addInterceptor {
                        val request = it.request()
                        if (request.name == "com.netease.nis.captcha.CaptchaWebView") {
                            val lollipopFixedDWebView = LollipopFixedCaptchaWebView(request.context, request.attrs)
                            return@addInterceptor InflateResult.builder()
                                .view(lollipopFixedDWebView)
                                .name(lollipopFixedDWebView.javaClass.name)
                                .context(request.context)
                                .attrs(request.attrs)
                                .build();
                        } else {
                            return@addInterceptor it.proceed(request)
                        }
                    }
                    .build()
            )
        }
```
在你使用了这个 `SDK` 的`Activity` 里添加：
```kotlin
   override fun attachBaseContext(newBase: Context?) {
        if (Build.VERSION.SDK_INT in 21..22) {
            super.attachBaseContext(ViewPumpContextWrapper.wrap(newBase))  
        }else{
            super.attachBaseContext(newBase)
        }
 }
```
问题解决。

**Comment by HuTianQi** [comment]
@z-chu 某些5.0机器存在该问题，以vivo机型居多，3.1.4版本已修复该问题，可使用新版本
