### ISSUE TITLE
isFinishing on a null object reference

### ISSUE THREAD

**Issue by ZhangKuixun** [yidun/captcha-android-demo#2]
FATAL EXCEPTION: main
                                                                             Process: com.zhixun.extraterrestrial, PID: 32647
                                                                             java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.Activity.isFinishing()' on a null object reference
                                                                                 at com.netease.nis.captcha.Captcha.start(Captcha.java:213)
                                                                                 at com.zhixun.extraterrestrial.ui.AJigsaw.lambda$onCreate$0$AJigsaw(AJigsaw.java:100)
                                                                                 at com.zhixun.extraterrestrial.ui.AJigsaw$$Lambda$0.onClick(Unknown Source:0)
                                                                                 at android.view.View.performClick(View.java:6294)
                                                                                 at android.view.View$PerformClick.run(View.java:24770)
                                                                                 at android.os.Handler.handleCallback(Handler.java:790)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                 at android.os.Looper.loop(Looper.java:164)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by HuTianQi** [comment]
请使用3.0.0及其以上的新SDK
