### ISSUE TITLE
Crash Error at com.netease.nis.captcha.Captcha$MyTask.run(Captcha.java:366)

### ISSUE THREAD

**Issue by Z-Seven** [yidun/captcha-android-demo#3]
version: 2.4.3.1
full error description：java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.sendMessage(android.os.Message)' on a null object reference
                      at com.netease.nis.captcha.Captcha$MyTask.run(Captcha.java:366)
                      at java.util.TimerThread.mainLoop(Timer.java:555)
                      at java.util.TimerThread.run(Timer.java:505)

when the network is slow or disconnection

**Comment by pzhangleo** [comment]
这问题很严重，尽快修复下吧

**Comment by pzhangleo** [comment]
这个把源码删了也是醉了啊，发现bug，自己改改都不行了

**Comment by HuTianQi** [comment]
请使用3.0.0及其以上新SDK
