### ISSUE TITLE
WindowManager$BadTokenException use v3.0.0

### ISSUE THREAD

**Issue by hamberluo** [yidun/captcha-android-demo#8]
```
Fatal Exception: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@ded9ef3 is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:884)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:372)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:128)
       at android.app.Dialog.show(Dialog.java:454)
       at com.netease.nis.captcha.d$3.run(Unknown Source:18)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**Comment by liulingfeng** [comment]
这个是Activity销毁还在弹窗吧
